<?php

namespace Database\Seeders;

use App\Models\MonitoredNetworkDevice;
use App\Models\SnmpDevice;
use App\Models\SnmpDeviceOid;
use App\Models\SnmpOid;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Crypt;

class SnmpOidsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $oids = [
            // MIB-II Estándar (RFC 1213)
            [
                'name' => 'sysDescr',
                'oid' => '1.3.6.1.2.1.1.1.0',
                'mib' => 'RFC1213-MIB',
                'vendor' => 'standard',
                'data_type' => 'string',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Descripción del sistema y versión de firmware',
            ],
            [
                'name' => 'sysObjectID',
                'oid' => '1.3.6.1.2.1.1.2.0',
                'mib' => 'RFC1213-MIB',
                'vendor' => 'standard',
                'data_type' => 'string',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Identificador formal del fabricante y arquitectura del dispositivo',
            ],
            [
                'name' => 'sysUpTime',
                'oid' => '1.3.6.1.2.1.1.3.0',
                'mib' => 'RFC1213-MIB',
                'vendor' => 'standard',
                'data_type' => 'timeticks',
                'unit' => 'ms',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Tiempo transcurrido desde el último reinicio del equipo',
            ],
            [
                'name' => 'sysContact',
                'oid' => '1.3.6.1.2.1.1.4.0',
                'mib' => 'RFC1213-MIB',
                'vendor' => 'standard',
                'data_type' => 'string',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Contacto administrativo del dispositivo',
            ],
            [
                'name' => 'sysName',
                'oid' => '1.3.6.1.2.1.1.5.0',
                'mib' => 'RFC1213-MIB',
                'vendor' => 'standard',
                'data_type' => 'string',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Nombre de host configurado en el dispositivo',
            ],
            [
                'name' => 'sysLocation',
                'oid' => '1.3.6.1.2.1.1.6.0',
                'mib' => 'RFC1213-MIB',
                'vendor' => 'standard',
                'data_type' => 'string',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Ubicación física o rack asignado al dispositivo',
            ],
            [
                'name' => 'ifNumber',
                'oid' => '1.3.6.1.2.1.2.1.0',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'integer',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Número total de interfaces de red presentes en el equipo',
            ],
            [
                'name' => 'ifIndex',
                'oid' => '1.3.6.1.2.1.2.2.1.1',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'integer',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Índice identificador de la interfaz de red',
            ],
            [
                'name' => 'ifDescr',
                'oid' => '1.3.6.1.2.1.2.2.1.2',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'string',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Nombre o descripción de la interfaz física (FastEthernet, Gigabit, etc.)',
            ],
            [
                'name' => 'ifType',
                'oid' => '1.3.6.1.2.1.2.2.1.3',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'integer',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Tipo de capa física de la interfaz (ethernetCsmacd, propVirtual, etc.)',
            ],
            [
                'name' => 'ifSpeed',
                'oid' => '1.3.6.1.2.1.2.2.1.5',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'gauge',
                'unit' => 'bps',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Velocidad nominal de la interfaz en bits por segundo',
            ],
            [
                'name' => 'ifPhysAddress',
                'oid' => '1.3.6.1.2.1.2.2.1.6',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'octets',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Dirección MAC física de la interfaz',
            ],
            [
                'name' => 'ifAdminStatus',
                'oid' => '1.3.6.1.2.1.2.2.1.7',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'integer',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Estado administrativo de la interfaz: 1=up, 2=down, 3=testing',
            ],
            [
                'name' => 'ifOperStatus',
                'oid' => '1.3.6.1.2.1.2.2.1.8',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'integer',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Estado operativo real de la interfaz (enlace físico activo)',
            ],
            [
                'name' => 'ifInOctets',
                'oid' => '1.3.6.1.2.1.2.2.1.10',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'counter',
                'unit' => 'bytes',
                'is_standard' => true,
                'is_counter_wrap' => true,
                'description' => 'Total de bytes de entrada recibidos por la interfaz (32 bits)',
            ],
            [
                'name' => 'ifOutOctets',
                'oid' => '1.3.6.1.2.1.2.2.1.16',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'counter',
                'unit' => 'bytes',
                'is_standard' => true,
                'is_counter_wrap' => true,
                'description' => 'Total de bytes de salida transmitidos por la interfaz (32 bits)',
            ],
            [
                'name' => 'ifInErrors',
                'oid' => '1.3.6.1.2.1.2.2.1.14',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'counter',
                'unit' => 'pkts',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Paquetes de entrada con errores detectados',
            ],
            [
                'name' => 'ifOutErrors',
                'oid' => '1.3.6.1.2.1.2.2.1.20',
                'mib' => 'IF-MIB',
                'vendor' => 'standard',
                'data_type' => 'counter',
                'unit' => 'pkts',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Paquetes de salida con errores detectados',
            ],
            [
                'name' => 'ipNetToMediaTable',
                'oid' => '1.3.6.1.2.1.4.22.1.2',
                'mib' => 'IP-MIB',
                'vendor' => 'standard',
                'data_type' => 'string',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Tabla ARP interna del switch/router para descubrimiento pasivo',
            ],

            // Cisco Específicos
            [
                'name' => 'ciscoCPU_5sec',
                'oid' => '1.3.6.1.4.1.9.2.1.56.0',
                'mib' => 'CISCO-PROCESS-MIB',
                'vendor' => 'Cisco',
                'data_type' => 'gauge',
                'unit' => '%',
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Utilización de CPU en los últimos 5 segundos',
            ],
            [
                'name' => 'ciscoCPU_1min',
                'oid' => '1.3.6.1.4.1.9.2.1.57.0',
                'mib' => 'CISCO-PROCESS-MIB',
                'vendor' => 'Cisco',
                'data_type' => 'gauge',
                'unit' => '%',
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Promedio de utilización de CPU en 1 minuto',
            ],
            [
                'name' => 'ciscoCPU_5min',
                'oid' => '1.3.6.1.4.1.9.2.1.58.0',
                'mib' => 'CISCO-PROCESS-MIB',
                'vendor' => 'Cisco',
                'data_type' => 'gauge',
                'unit' => '%',
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Promedio de utilización de CPU en 5 minutos',
            ],
            [
                'name' => 'ciscoMemPoolUsed',
                'oid' => '1.3.6.1.4.1.9.9.48.1.1.1.5',
                'mib' => 'CISCO-MEMORY-POOL-MIB',
                'vendor' => 'Cisco',
                'data_type' => 'gauge',
                'unit' => 'bytes',
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Memoria RAM utilizada en el procesador principal',
            ],
            [
                'name' => 'ciscoMemPoolFree',
                'oid' => '1.3.6.1.4.1.9.9.48.1.1.1.6',
                'mib' => 'CISCO-MEMORY-POOL-MIB',
                'vendor' => 'Cisco',
                'data_type' => 'gauge',
                'unit' => 'bytes',
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Memoria RAM libre disponible',
            ],
            [
                'name' => 'ciscoTempValue',
                'oid' => '1.3.6.1.4.1.9.9.13.1.3.1.3',
                'mib' => 'CISCO-ENVMON-MIB',
                'vendor' => 'Cisco',
                'data_type' => 'gauge',
                'unit' => '°C',
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Temperatura interna del chasis o CPU',
            ],
            [
                'name' => 'ciscoEnvMonState',
                'oid' => '1.3.6.1.4.1.9.9.13.1.2.1.3',
                'mib' => 'CISCO-ENVMON-MIB',
                'vendor' => 'Cisco',
                'data_type' => 'integer',
                'unit' => null,
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Estado ambiental de fuentes y ventiladores (1=normal, 2=warning, 3=critical)',
            ],
            [
                'name' => 'ciscoCDPNeighbors',
                'oid' => '1.3.6.1.4.1.9.9.23.1.2.1.1.6',
                'mib' => 'CISCO-CDP-MIB',
                'vendor' => 'Cisco',
                'data_type' => 'string',
                'unit' => null,
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Identificador de dispositivos vecinos detectados por CDP',
            ],
            [
                'name' => 'ciscoLLDPRemSysName',
                'oid' => '1.0.8802.1.1.2.1.4.1.1.9',
                'mib' => 'LLDP-MIB',
                'vendor' => 'standard',
                'data_type' => 'string',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Nombre de host de vecinos detectados vía protocolo LLDP',
            ],

            // Genéricos (HOST-RESOURCES-MIB)
            [
                'name' => 'hrProcessorLoad',
                'oid' => '1.3.6.1.2.1.25.3.3.1.2',
                'mib' => 'HOST-RESOURCES-MIB',
                'vendor' => 'standard',
                'data_type' => 'gauge',
                'unit' => '%',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Carga porcentual por procesador o núcleo',
            ],
            [
                'name' => 'hrMemorySize',
                'oid' => '1.3.6.1.2.1.25.2.2.0',
                'mib' => 'HOST-RESOURCES-MIB',
                'vendor' => 'standard',
                'data_type' => 'gauge',
                'unit' => 'KB',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Tamaño total de la memoria RAM del host',
            ],
            [
                'name' => 'hrStorageUsed',
                'oid' => '1.3.6.1.2.1.25.2.3.1.6',
                'mib' => 'HOST-RESOURCES-MIB',
                'vendor' => 'standard',
                'data_type' => 'counter',
                'unit' => 'units',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Espacio de almacenamiento ocupado en bloques',
            ],
            [
                'name' => 'hrStorageSize',
                'oid' => '1.3.6.1.2.1.25.2.3.1.5',
                'mib' => 'HOST-RESOURCES-MIB',
                'vendor' => 'standard',
                'data_type' => 'counter',
                'unit' => 'units',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Tamaño total del almacenamiento en bloques',
            ],

            // UPS (UPS-MIB / APC)
            [
                'name' => 'upsBatteryStatus',
                'oid' => '1.3.6.1.2.1.33.1.2.1.0',
                'mib' => 'UPS-MIB',
                'vendor' => 'APC',
                'data_type' => 'integer',
                'unit' => null,
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Estado de batería (1=desconocido, 2=normal, 3=baja, 4=agotada)',
            ],
            [
                'name' => 'upsEstimatedMinutesRemaining',
                'oid' => '1.3.6.1.2.1.33.1.2.3.0',
                'mib' => 'UPS-MIB',
                'vendor' => 'APC',
                'data_type' => 'gauge',
                'unit' => 'min',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Minutos estimados de autonomía con la carga eléctrica actual',
            ],
            [
                'name' => 'upsBatteryCharge',
                'oid' => '1.3.6.1.2.1.33.1.2.4.0',
                'mib' => 'UPS-MIB',
                'vendor' => 'APC',
                'data_type' => 'gauge',
                'unit' => '%',
                'is_standard' => true,
                'is_counter_wrap' => false,
                'description' => 'Porcentaje de carga restante en el banco de baterías',
            ],
            [
                'name' => 'upsAdvBatteryCapacity',
                'oid' => '1.3.6.1.4.1.318.1.1.1.2.2.1.0',
                'mib' => 'PowerNet-MIB',
                'vendor' => 'APC',
                'data_type' => 'gauge',
                'unit' => '%',
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Capacidad porcentual de batería APC PowerNet',
            ],

            // pfSense (Net-SNMP / FreeBSD)
            [
                'name' => 'pfStateCount',
                'oid' => '1.3.6.1.4.1.12325.1.200.1.2.0',
                'mib' => 'BEGEMOT-PF-MIB',
                'vendor' => 'pfSense',
                'data_type' => 'gauge',
                'unit' => 'estados',
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Total de estados activos en la tabla de estado del firewall pf',
            ],
            [
                'name' => 'pfStateLimit',
                'oid' => '1.3.6.1.4.1.12325.1.200.1.3.0',
                'mib' => 'BEGEMOT-PF-MIB',
                'vendor' => 'pfSense',
                'data_type' => 'gauge',
                'unit' => 'estados',
                'is_standard' => false,
                'is_counter_wrap' => false,
                'description' => 'Límite máximo configurado de estados simultáneos en pfSense',
            ],
        ];

        foreach ($oids as $data) {
            SnmpOid::updateOrCreate(
                ['oid' => $data['oid']],
                $data
            );
        }

        // Sembrar dispositivos clave desde monitored_network_devices si no existen en snmp_devices
        $devicesToSync = [
            [
                'name' => 'Switch Core Valle Seco (C3750)',
                'ip_address' => '10.20.23.1',
                'device_type' => 'switch',
                'vendor' => 'Cisco',
                'model' => 'WS-C3750-24TS',
                'snmp_version' => 'v2c',
                'community' => 'public',
            ],
            [
                'name' => 'Switch Distribución Taquilla (C2960)',
                'ip_address' => '10.20.23.4',
                'device_type' => 'switch',
                'vendor' => 'Cisco',
                'model' => 'WS-C2960-24TT-L',
                'snmp_version' => 'v2c',
                'community' => 'public',
            ],
            [
                'name' => 'Firewall pfSense Valle Seco',
                'ip_address' => '10.20.23.252',
                'device_type' => 'firewall',
                'vendor' => 'pfSense',
                'model' => 'Netgate SG-3100',
                'snmp_version' => 'v2c',
                'community' => 'public',
            ],
            [
                'name' => 'Router Gateway Carabobo',
                'ip_address' => '10.20.0.1',
                'device_type' => 'router',
                'vendor' => 'Cisco',
                'model' => 'Cisco 2901',
                'snmp_version' => 'v2c',
                'community' => 'public',
            ],
            [
                'name' => 'SW01 - Cisco Principal',
                'ip_address' => '10.20.23.2',
                'device_type' => 'switch',
                'vendor' => 'Cisco',
                'model' => 'Catalyst 2960-X',
                'snmp_version' => 'v2c',
                'community' => 'public',
            ],
            [
                'name' => 'SW03 - Cisco Servidores',
                'ip_address' => '10.20.23.5',
                'device_type' => 'switch',
                'vendor' => 'Cisco',
                'model' => 'Catalyst 2960-S',
                'snmp_version' => 'v2c',
                'community' => 'public',
            ],
            [
                'name' => 'EQUIPO 03 - Switch Transmisión',
                'ip_address' => '10.20.27.83',
                'device_type' => 'switch',
                'vendor' => 'Cisco',
                'model' => 'Catalyst 2960',
                'snmp_version' => 'v2c',
                'community' => 'public',
            ],
            [
                'name' => 'Switch CIAU Consolidado',
                'ip_address' => '10.20.107.131',
                'device_type' => 'switch',
                'vendor' => 'Cisco',
                'model' => 'Catalyst 2960',
                'snmp_version' => 'v2c',
                'community' => 'public',
            ],
            [
                'name' => 'Switch/Gateway CIAU Morón',
                'ip_address' => '10.20.106.193',
                'device_type' => 'switch',
                'vendor' => 'Cisco',
                'model' => 'Cisco 2901 / Switch Sede',
                'snmp_version' => 'v2c',
                'community' => 'public',
            ],
        ];

        $allOidModels = SnmpOid::whereIn('name', [
            'sysDescr', 'sysUpTime', 'sysName', 'ciscoCPU_5min', 'ciscoMemPoolFree',
            'hrProcessorLoad', 'pfStateCount'
        ])->get();

        foreach ($devicesToSync as $devInfo) {
            $netDev = MonitoredNetworkDevice::where('ip', $devInfo['ip_address'])->first();

            $snmpDev = SnmpDevice::updateOrCreate(
                ['ip_address' => $devInfo['ip_address']],
                [
                    'name' => $devInfo['name'],
                    'device_type' => $devInfo['device_type'],
                    'vendor' => $devInfo['vendor'],
                    'model' => $devInfo['model'],
                    'snmp_version' => $devInfo['snmp_version'],
                    'snmp_community_encrypted' => $devInfo['community'],
                    'snmp_port' => 161,
                    'snmp_timeout_seconds' => 5,
                    'snmp_retries' => 2,
                    'poll_interval_seconds' => 60,
                    'is_active' => true,
                    'network_device_id' => $netDev?->id,
                    'site_id' => $netDev?->monitored_site_id,
                ]
            );

            // Asociar OIDs esenciales
            foreach ($allOidModels as $o) {
                SnmpDeviceOid::updateOrCreate(
                    [
                        'snmp_device_id' => $snmpDev->id,
                        'snmp_oid_id' => $o->id,
                    ],
                    [
                        'is_active' => true,
                        'alert_threshold_warning' => 80.0,
                        'alert_threshold_critical' => 95.0,
                    ]
                );
            }
        }
    }
}
