# ==============================================================================
# 🤖 CONFIGURACIÓN DEL BOT: bot.conf (@IA_ValleSeco_bot)
# Ubicación: /scripts/telegram-admin-bot/config/bot.conf
# Sistema Objetivo: Debian 12 / 13 GNU/Linux (amd64) o Ubuntu Server
# License: GNU Affero General Public License v3.0 
# Author: Jose A. Brito H. (@britojab:@britojq), https://britojab.com
# Copyright (c) 2026 Jose A. Brito H.
# ==============================================================================

## ARCHIVO DE CONFIGURACION DEL BOT (TODO LO NECESARIO PARA ENVIAR MENSAJES AL BOT)

#########################################################################################

### TOKEN DEL BOT (ESTA ES LA IDENTIFICACION QUE TE ENTREGA TELEGRAM AL CREAR EL BOT)
## TOKEN VALLE SECO BOT
#TOKENA=1595888148:AAEMMMmCAV1I5EaUMkTQ3uVBJ2LpK9aIAoQ
TOKENA=8791276974:AAH3dbTjj8T76tf_QAiPql1iWYsrd8NI3nU

## PARA ENVIO DE MENSAJE EN TELEGRAM (SOLO TEXTO)
URLPOST=https://api.telegram.org/bot$TOKENA/sendMessage

## PARA ENVIO DE MENSAJE EN TELEGRAM (SOLO IMAGEN)
URLPOSTF=https://api.telegram.org/bot$TOKENA/sendPhoto

## PARA ENVIO DE MENSAJE EN TELEGRAM (SOLO ARCHIVOS)
URLPOSTDOC=https://api.telegram.org/bot$TOKENA/sendDocument?chat_id=$IDCHAT

#########################################################################################
### ID DEL GRUPO DONDE SE ENVIARA EL MENSAJE
#IDA="-1001383163558"
IDA="38914901"
### ID DEL PROPIETARIO DEL BOT
IDC="38914901"

#########################################################################################

### SITIO WEB QUE SE UTILIZARA PARA VERIFICAR QUE PUEDE NAVEGAR POR PROXY
DEFAULTURLCONTROL='https://core.telegram.org/bots'

###### PROXY A
NAMEPROXYA="Squid - Dansguardian - CARABOBO"
IPADDRPORTPROXYA='10.20.0.89:8080'
USERPASSWDPROXYA='A1746281:Abrito2026.*'

###### PROXY B
NAMEPROXYB="Squid - Dansguardian - VALLE SECO"
IPADDRPORTPROXYB='10.20.23.65:8080'
USERPASSWDPROXYB='jbrito:Octubre2022.'

###### PROXY C
NAMEPROXYC="PFsense - CARABOBO (119)"
IPADDRPORTPROXYC='10.20.0.119:8080'
USERPASSWDPROXYC='A1746281:Abrito2026.*'

###### PROXY D
NAMEPROXYD="PFsense - CARABOBO (89)"
IPADDRPORTPROXYD='10.20.0.89:8080'
USERPASSWDPROXYD='A1746281:Abrito2026.*'

