# ==============================================================================
# 🌐 CONFIGURACIÓN DE PROXIES: bot.conf
# Sincronizado automáticamente desde el Panel Web ATIT Valle Seco
# ==============================================================================
NAMEPROXYA="Squid - Dansguardian - CARABOBO"
IPADDRPORTPROXYA=10.20.0.89:8080
USERPASSWDPROXYA=A1746281:Abrito2026.*
NAMEPROXYB="Squid - Dansguardian - VALLE SECO"
IPADDRPORTPROXYB=10.20.23.65:8080
USERPASSWDPROXYB=jbrito:Octubre2022.
NAMEPROXYC="PFsense - CARABOBO (119)"
IPADDRPORTPROXYC=10.20.0.119:8080
USERPASSWDPROXYC=A1746281:Abrito2026.*
NAMEPROXYD="PFsense - CARABOBO (89)"
IPADDRPORTPROXYD=10.20.0.89:8080
USERPASSWDPROXYD=A1746281:Abrito2026.*
